#ifndef PYGLSLANG_ENUMS_H
#define PYGLSLANG_ENUMS_H

enum enums {
    STAGE_VERT = 0,
    STAGE_TESC = 1,
    STAGE_TESE = 2,
    STAGE_GEOM = 3,
    STAGE_FRAG = 4,
    STAGE_COMP = 5
};

enum NodeKind {
    KIND_ROOT,
    KIND_SYMBOL,
    KIND_UNION,
    KIND_BINARY,
    KIND_UNARY,
    KIND_SELECTION,
    KIND_AGGREGATE,
    KIND_LOOP,
    KIND_BRANCH,
    KIND_SWITCH,
    KIND_VAR_DECL,
};

#endif //PYGLSLANG_ENUMS_H
